In [10]:
import  pandas as pd

df_1 = pd.read_csv('/Users/meetnakrani/Library/Mobile Documents/com~apple~CloudDocs/recommendation-engine-platform/data/raw/ml-32m/links.csv')
df_1.head()
df_1.shape
df_1.info()
df_1.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87585 entries, 0 to 87584
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  87585 non-null  int64
 1   imdbId   87585 non-null  int64
 2   tmdbId   87461 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 2.0 MB

             movieId        imdbId        tmdbId
count   87585.000000  8.758500e+04  8.746100e+04
mean   157651.365519  2.792840e+06  2.413823e+05
std     79013.402099  4.278866e+06  2.471467e+05
min         1.000000  1.000000e+00  2.000000e+00
25%    112657.000000  9.464200e+04  4.683600e+04
50%    165741.000000  4.929960e+05  1.392720e+05
75%    213203.000000  3.877296e+06  3.816930e+05
max    292757.000000  2.908110e+07  1.186337e+06

In [15]:
df_2 = pd.read_csv('/Users/meetnakrani/Library/Mobile Documents/com~apple~CloudDocs/recommendation-engine-platform/data/raw/ml-32m/movies.csv')
df_2.head()
df_2.shape
df_2.info()
df_2.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87585 entries, 0 to 87584
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  87585 non-null  int64
 1   title    87585 non-null  object
 2   genres   87585 non-null  object
dtypes: int64(1), object(2)
memory usage: 2.0+ MB

             movieId
count   87585.000000
mean   157651.365519
std     79013.402099
min         1.000000
25%    112657.000000
50%    165741.000000
75%    213203.000000
max    292757.000000

In [21]:
df_3 = pd.read_csv('/Users/meetnakrani/Library/Mobile Documents/com~apple~CloudDocs/recommendation-engine-platform/data/raw/ml-32m/ratings.csv')
df_3.head()
df_3.shape
df_3.info()
df_3.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32000204 entries, 0 to 32000203
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
dtypes: float64(1), int64(3)
memory usage: 976.6 MB

             userId       movieId        rating     timestamp
count  3.200020e+07  3.200020e+07  3.200020e+07  3.200020e+07
mean   1.002785e+05  2.931861e+04  3.540396e+00  1.275241e+09
std    5.794905e+04  5.095816e+04  1.058986e+00  2.561630e+08
min    1.000000e+00  1.000000e+00  5.000000e-01  7.896520e+08
25%    5.005300e+04  1.233000e+03  3.000000e+00  1.051012e+09
50%    1.002970e+05  3.452000e+03  3.500000e+00  1.272622e+09
75%    1.504510e+05  4.419900e+04  4.000000e+00  1.503158e+09
max    2.009480e+05  2.927570e+05  5.000000e+00  1.697164e+09

In [25]:
df_4 = pd.read_csv('/Users/meetnakrani/Library/Mobile Documents/com~apple~CloudDocs/recommendation-engine-platform/data/raw/ml-32m/tags.csv')
df_4.head()
df_4.shape
df_4.info()
df_4.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000072 entries, 0 to 2000071
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   tag        object
 3   timestamp  int64
dtypes: int64(3), object(1)
memory usage: 61.0+ MB

             userId       movieId     timestamp
count  2.000072e+06  2.000072e+06  2.000072e+06
mean   8.192859e+04  7.189326e+04  1.528914e+09
std    3.810650e+04  7.480379e+04  1.290835e+08
min    2.200000e+01  1.000000e+00  1.135429e+09
25%    6.841300e+04  4.011000e+03  1.473615e+09
50%    7.821300e+04  5.232800e+04  1.574071e+09
75%    1.036980e+05  1.222940e+05  1.614740e+09
max    1.622790e+05  2.926290e+05  1.697155e+09